---
title: Kenny Chua - Polyglot Problem Solver
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Kenny Chua - Polyglot Problem Solver
baseurl: ''
url: https://kennychua.github.io
username: Kenny Chua
user_description: I solve difficult problems.. people, process & technology
user_title: Polyglot Problem Solver
email: mail@kennychua.net
twitter_username: spazkus
github_username: kennychua
markdown: kramdown
highlighter: rouge
permalink: "/:title/"
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false
links:
- title: Home
  url: "/"
- title: Tags
  url: "/tags"
- title: About Me
  url: "/about"
exclude:
- package.json
- src
- node_modules
